### ISSUE TITLE
Missing compiler required member

### ISSUE THREAD

**Issue by KenMacD** [maddnias/NETDeob#1]
Hello,

I'm attempting to build on Win7 using Microsoft Visual C# 2010 Express with .NET 4. The errors I'm seeing are:

```
Missing compiler required member 'System.Runtime.CompilerServices.ExtensionAttribute..ctor' 
```

There's also a warning for: 

```
The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'NETDeob\Mono.Cecil.dll'
```

I tried using a newer version of Mono.Cecil, but that didn't work for other reasons.

**Comment by maddnias** [comment]
Yeah, i've had that error for a while. To be honest i'm not sure how to get rid of it properly, but you can fix it by removing the Mono.Cecil reference in both NETDeob.Console and NETDeob.Core then re-adding it.

**Comment by KenMacD** [comment]
That worked, ty. No idea why though.

**Comment by KenMacD** [comment]
Tested the branch, worked great. Thanks.
