### ISSUE TITLE
Result file is 0KB

### ISSUE THREAD

**Issue by esolution** [maddnias/NETDeob#4]
I tried to deobfuscate an exe using the classic drag and drop method. The detection went well and the process finished but the result deobfuscated file is 0KB:

NETDeob 0.3.1 BETA

Obfuscator identified: Phoenix Protector
## Cleaning assembly...

Performing routine:

Phase 1: Clean Control Flow (de4dot)
127 methods cleaned...

Performing routine: String decryption

Phase 1: Locating decryptor method
Found string decryptor method at Method3...

Phase 2: Construct entries
0 decryption entries constructed...

Phase 3: Decrypt strings
0 strings decrypted...

Phase 4: Process entries
All entries processed...

Performing routine: Symbol renaming

Phase 1: Renaming symbols
Renaming symbols...

Performing routine: Remove bad members

Phase 1: Strip assembly from bad members
7 members cleaned from assembly...

---

Successfully deobfuscated assembly: YT in 254 milliseconds

Deobfuscated assembly saved at: C:\NETDeob\YT_deobf.exe
Contact author!

The initial file is 45KB

**Comment by maddnias** [comment]
What obfuscator was used on the assembly?

**Comment by esolution** [comment]
I have no idea, this was not a test to see if your software can deobfuscate a certain obfuscator ... I just need an assembly deobfuscate ... your software detected Phoenix Protector ...

**Comment by maddnias** [comment]
That doesn't help me at all... If you know what obfuscator was used, and if it's supported by NETDeob you can download and modify the source to detect that specific obfuscator instead of Phoenix.

**Comment by esolution** [comment]
how can I find what  obfuscator was used?

**Comment by maddnias** [comment]
If you don't know, and it detects Phoenix then it's probably not supported by NETDeob. Try https://bitbucket.org/0xd4d/de4dot/.
